"""
bubo/brain/motor/gesture_engine.py — Bubo v10000

Expressive Gesture Engine: Head, Torso, and Arm Gestures

════════════════════════════════════════════════════════════════════
THE NEUROSCIENCE OF GESTURE
════════════════════════════════════════════════════════════════════

Human gesture is not decoration. It is a primary communication
channel that carries approximately 55% of emotional meaning
(Mehrabian 1967 — the original source of the often-misquoted 55/38/7).

Gestures are generated by the premotor cortex (SMA/PM) and are:
  1. Co-produced with speech (beat gestures, iconic gestures)
  2. Driven by emotional state (affective gestures)
  3. Modulatory — they change the meaning of the accompanying speech

For Bubo, gestures serve THREE purposes:
  SOCIAL: communicate emotional state and engagement to humans
  COGNITIVE: embodied thinking — gesture helps Bubo think
  SAFETY: always secondary to functional arm tasks

════════════════════════════════════════════════════════════════════
GESTURE PRIORITY SYSTEM
════════════════════════════════════════════════════════════════════

PRIORITY 1 — SAFETY: Never gesture while:
  - Carrying an object (both arms occupied)
  - Grasping with any hand (active grasp)
  - Within 20cm of a human (peripersonal space, S1 report)
  - Balance is compromised (IMU roll/pitch > 5°)

PRIORITY 2 — TASK COMPLETION: If one arm is in use, only the
  FREE arm and head/torso gestures are permitted.

PRIORITY 3 — EMOTIONAL EXPRESSION: When fully free, both arms
  and full-body expression is available.

PRIORITY 4 — IDLE ANIMATION: Subtle micro-movements when no
  interaction is occurring (prevents the "dead robot" uncanny valley).

════════════════════════════════════════════════════════════════════
GESTURE VOCABULARY
════════════════════════════════════════════════════════════════════

HEAD gestures (highest expressiveness per unit movement):
  NOD:          agreement, acknowledgement, "yes"
  SHAKE:        disagreement, "no"
  TILT_LEFT:    curiosity, thinking, processing
  TILT_RIGHT:   listening, empathy
  BOW:          greeting, gratitude
  LOOK_DOWN:    shame, thinking deeply
  LOOK_UP:      recall, imagination, hope

TORSO gestures:
  LEAN_FORWARD: engagement, curiosity, excitement ("input!")
  LEAN_BACK:    surprise, uncertainty, taking stock
  UPRIGHT:      neutral, confident, ready
  SLIGHT_BOW:   greeting, respect

ARM gestures (when arms are free):
  OPEN_ARMS:    welcoming, inclusive, "come here"
  ARMS_OUT:     explaining/presenting something
  RAISE_ONE:    offering, pointing, "look at this"
  CROSSED:      thinking, self-contained (low arousal states)
  HANDS_UP:     surprise, "I don't know", uncertainty
  GESTURE_SPEECH: subtle wrist movements during speaking

COMBINED / SIGNATURE GESTURES:
  GREETING:     bow + open arms (meeting someone new, bond_level < 0.3)
  RECOGNITION:  slight lean forward + head tilt (seeing familiar person)
  DEEP_THOUGHT: tilt head + one hand near chin (processing hard question)
  DELIGHT:      lean forward + hands out + eye cover flutter
  LISTENING:    tilt right + lean slightly forward + stillness
"""

import time
import threading
import logging
import numpy as np
from dataclasses import dataclass, field
from typing import Optional, List, Callable
from enum import Enum

logger = logging.getLogger("GestureEngine")


class GesturePriority(Enum):
    IDLE      = 0
    EMOTIONAL = 1
    SPEECH    = 2
    SAFETY    = 3   # highest — overrides all


@dataclass
class ArmState:
    """Current arm occupancy state — fed from spinal_arms node."""
    left_grasping:  bool  = False
    right_grasping: bool  = False
    left_carrying:  bool  = False
    right_carrying: bool  = False
    near_human:     bool  = False   # from peripersonal space monitor
    balance_ok:     bool  = True


@dataclass
class GestureCommand:
    """A gesture to execute."""
    name:           str
    priority:       GesturePriority = GesturePriority.EMOTIONAL
    duration_s:     float = 1.0
    head_nod:       float = 0.0    # degrees forward/back
    head_shake:     float = 0.0    # degrees left/right oscillation
    head_tilt_l:    float = 0.0    # degrees tilt left
    head_tilt_r:    float = 0.0    # degrees tilt right
    head_raise:     float = 0.0    # look up/down
    torso_lean:     float = 0.0    # forward (+) / back (-)
    arm_l_raise:    float = 0.0    # left arm raise degrees
    arm_r_raise:    float = 0.0    # right arm raise
    arm_l_spread:   float = 0.0    # left arm out to side
    arm_r_spread:   float = 0.0    # right arm out to side
    wrist_l_rotate: float = 0.0    # expressive wrist
    wrist_r_rotate: float = 0.0


# ── Gesture library ───────────────────────────────────────────────────────────

GESTURES: dict[str, GestureCommand] = {

    # ── Head only ─────────────────────────────────────────────────────────────
    "nod": GestureCommand(
        name="nod", duration_s=0.8,
        head_nod=15.0,   # two quick nods
    ),
    "double_nod": GestureCommand(
        name="double_nod", duration_s=1.2,
        head_nod=15.0,
    ),
    "head_shake_no": GestureCommand(
        name="head_shake_no", duration_s=1.0,
        head_shake=20.0,
    ),
    "tilt_curious": GestureCommand(
        name="tilt_curious", duration_s=1.5,
        head_tilt_l=18.0,
        torso_lean=3.0,  # slight forward lean adds to curiosity
    ),
    "tilt_listening": GestureCommand(
        name="tilt_listening", duration_s=2.0,
        head_tilt_r=12.0,
        torso_lean=4.0,
    ),
    "look_up_recall": GestureCommand(
        name="look_up_recall", duration_s=2.0,
        head_raise=-15.0,  # look up (negative = up)
        head_tilt_l=8.0,
    ),
    "look_down_shame": GestureCommand(
        name="look_down_shame", duration_s=1.5,
        head_raise=20.0,   # look down
    ),
    "bow_greeting": GestureCommand(
        name="bow_greeting", duration_s=1.5,
        head_raise=25.0,   # head down
        torso_lean=15.0,   # forward bow
    ),

    # ── Torso ─────────────────────────────────────────────────────────────────
    "lean_forward_engaged": GestureCommand(
        name="lean_forward_engaged", duration_s=0.5,
        torso_lean=8.0, head_tilt_l=5.0,
    ),
    "lean_back_surprised": GestureCommand(
        name="lean_back_surprised", duration_s=0.4,
        torso_lean=-12.0, head_raise=-8.0,
    ),

    # ── Arms (require checking ArmState first) ───────────────────────────────
    "open_arms_welcome": GestureCommand(
        name="open_arms_welcome", duration_s=2.0,
        arm_l_spread=50.0, arm_r_spread=50.0,
        torso_lean=5.0,
    ),
    "arms_presenting": GestureCommand(
        name="arms_presenting", duration_s=2.5,
        arm_l_raise=30.0, arm_r_raise=30.0,
        arm_l_spread=25.0, arm_r_spread=25.0,
        wrist_l_rotate=10.0, wrist_r_rotate=10.0,
    ),
    "hands_up_uncertain": GestureCommand(
        name="hands_up_uncertain", duration_s=1.5,
        arm_l_raise=60.0, arm_r_raise=60.0,
        wrist_l_rotate=15.0, wrist_r_rotate=15.0,
        torso_lean=-5.0,
    ),
    "one_arm_point": GestureCommand(
        name="one_arm_point", duration_s=1.5,
        arm_r_raise=45.0, arm_r_spread=20.0,
    ),
    "speech_wrist_l": GestureCommand(
        name="speech_wrist_l", duration_s=0.8,
        wrist_l_rotate=20.0, arm_l_raise=15.0,
    ),
    "speech_wrist_r": GestureCommand(
        name="speech_wrist_r", duration_s=0.8,
        wrist_r_rotate=20.0, arm_r_raise=15.0,
    ),

    # ── Compound / signature ──────────────────────────────────────────────────
    "greeting_full": GestureCommand(
        name="greeting_full", duration_s=2.5,
        head_raise=20.0, torso_lean=12.0,     # bow
        arm_l_spread=30.0, arm_r_spread=30.0, # open arms
    ),
    "recognition_warm": GestureCommand(
        name="recognition_warm", duration_s=1.0,
        torso_lean=6.0, head_tilt_l=8.0,
    ),
    "deep_thought": GestureCommand(
        name="deep_thought", duration_s=3.0,
        head_tilt_l=15.0, head_raise=-5.0,
        arm_r_raise=20.0,  # hand near chin
    ),
    "delight": GestureCommand(
        name="delight", duration_s=1.5,
        torso_lean=10.0,
        arm_l_raise=25.0, arm_r_raise=25.0,
        arm_l_spread=20.0, arm_r_spread=20.0,
        head_tilt_l=8.0,
    ),
    "idle_micro_left": GestureCommand(
        name="idle_micro_left", priority=GesturePriority.IDLE,
        duration_s=2.0, head_tilt_l=5.0,
    ),
    "idle_micro_right": GestureCommand(
        name="idle_micro_right", priority=GesturePriority.IDLE,
        duration_s=2.0, head_tilt_r=4.0,
    ),
    "idle_breathe": GestureCommand(
        name="idle_breathe", priority=GesturePriority.IDLE,
        duration_s=3.0, torso_lean=2.0,  # subtle chest rise
    ),
}


# ── Emotion → gesture mapping ─────────────────────────────────────────────────

EMOTION_GESTURES = {
    "joy":        ["delight", "lean_forward_engaged"],
    "sadness":    ["look_down_shame", "tilt_listening"],
    "fear":       ["lean_back_surprised", "hands_up_uncertain"],
    "anger":      ["head_shake_no"],
    "surprise":   ["lean_back_surprised", "hands_up_uncertain"],
    "curiosity":  ["tilt_curious", "lean_forward_engaged"],
    "empathy":    ["tilt_listening", "lean_forward_engaged"],
    "contentment":["idle_breathe"],
    "excitement": ["delight", "open_arms_welcome"],
    "confusion":  ["tilt_curious", "deep_thought"],
    "loneliness": ["look_down_shame"],
    "pride":      ["lean_forward_engaged"],
    "shame":      ["look_down_shame"],
    "disgust":    ["lean_back_surprised", "head_shake_no"],
    "neutral":    ["idle_micro_left", "idle_breathe"],
}

# Gestures that require free arms
ARM_GESTURES = {
    "open_arms_welcome", "arms_presenting", "hands_up_uncertain",
    "one_arm_point", "speech_wrist_l", "speech_wrist_r",
    "delight", "greeting_full",
}


class GestureEngine:
    """
    Expressive gesture controller for Bubo's head, torso, and arms.
    
    Integrates with:
      - EmotionChip (AffectiveState → gesture selection)
      - SpinalArms (ArmState → safety gating)
      - PFC speech output (beat gestures during speech)
      - Oculomotor (head position coordination with VOR)
      - FriendshipEngine (greeting intensity by bond_level)
    """

    IDLE_INTERVAL_S = 8.0   # time between idle micro-gestures

    def __init__(self, speak_fn: Optional[Callable] = None, bus=None):
        self._speak   = speak_fn
        self._bus     = bus
        self._arm_state = ArmState()
        self._running   = False
        self._current_gesture = None
        self._gesture_q: List[GestureCommand] = []
        self._lock      = threading.Lock()
        self._last_gesture_t = time.time()
        self._last_emotion = "neutral"

    def on_emotion_update(self, emotion: str, intensity: float):
        """Called when EmotionChip updates affective state."""
        if emotion == self._last_emotion: return
        self._last_emotion = emotion

        candidate_gestures = EMOTION_GESTURES.get(emotion, ["idle_micro_left"])
        # Pick appropriate gesture based on arm availability
        for gname in candidate_gestures:
            gcmd = GESTURES.get(gname)
            if gcmd and self._is_safe(gcmd):
                self.queue(gcmd)
                break

    def on_speech_start(self, text: str):
        """Add a beat gesture when Bubo starts speaking."""
        if "?" in text:
            # Question → tilt + one wrist
            if self._arm_state_allows_arm_gesture():
                self.queue(GESTURES["tilt_curious"])
        elif len(text) > 50:
            # Longer statement → presenting gesture
            if self._arm_state_allows_arm_gesture():
                self.queue(GESTURES["speech_wrist_r"])

    def on_person_recognised(self, person_name: str, bond_level: float):
        """Greeting gesture scaled by bond level."""
        if bond_level > 0.5:
            self.queue(GESTURES["recognition_warm"])
        elif bond_level > 0.2:
            self.queue(GESTURES["tilt_listening"])
        else:
            if self._arm_state_allows_arm_gesture():
                self.queue(GESTURES["greeting_full"])
            else:
                self.queue(GESTURES["bow_greeting"])

    def on_question_received(self, question: str):
        """Bubo received a complex question — thinking gesture."""
        self.queue(GESTURES["deep_thought"])

    def on_arm_state_update(self, arm_state: ArmState):
        """Update from spinal_arms node."""
        with self._lock:
            self._arm_state = arm_state

    def queue(self, gesture: GestureCommand):
        """Queue a gesture for execution."""
        with self._lock:
            # Higher priority bumps lower priority items
            self._gesture_q = [g for g in self._gesture_q
                                if g.priority.value >= gesture.priority.value]
            self._gesture_q.append(gesture)

    def _is_safe(self, gcmd: GestureCommand) -> bool:
        """Safety gate — check if this gesture is safe to execute now."""
        with self._lock:
            s = self._arm_state
        if not s.balance_ok:        return False
        if s.near_human:            return False
        if gcmd.name in ARM_GESTURES:
            if s.left_grasping or s.right_grasping: return False
            if s.left_carrying or s.right_carrying: return False
        return True

    def _arm_state_allows_arm_gesture(self) -> bool:
        with self._lock:
            s = self._arm_state
        return (not s.left_grasping and not s.right_grasping and
                not s.left_carrying and not s.right_carrying and
                not s.near_human and s.balance_ok)

    def _execute(self, gcmd: GestureCommand):
        """Execute a gesture by publishing joint targets to ZMQ bus."""
        if not self._is_safe(gcmd):
            logger.debug(f"Gesture '{gcmd.name}' blocked by safety gate")
            return

        logger.info(f"Gesture: {gcmd.name} ({gcmd.duration_s:.1f}s)")
        self._last_gesture_t = time.time()
        self._current_gesture = gcmd.name

        if self._bus:
            # Publish head target
            if abs(gcmd.head_nod) + abs(gcmd.head_shake) + \
               abs(gcmd.head_tilt_l) + abs(gcmd.head_tilt_r) + \
               abs(gcmd.head_raise) > 0:
                self._bus.publish(b"CTX_HEAD_GESTURE", {
                    "nod":     gcmd.head_nod,
                    "shake":   gcmd.head_shake,
                    "tilt_l":  gcmd.head_tilt_l,
                    "tilt_r":  gcmd.head_tilt_r,
                    "raise":   gcmd.head_raise,
                    "duration_s": gcmd.duration_s,
                    "source":  "gesture_engine",
                })

            # Publish torso lean
            if abs(gcmd.torso_lean) > 0:
                self._bus.publish(b"CTX_TORSO_GESTURE", {
                    "lean":      gcmd.torso_lean,
                    "duration_s":gcmd.duration_s,
                    "source":    "gesture_engine",
                })

            # Publish arm targets (only if safe)
            if self._arm_state_allows_arm_gesture():
                if any([gcmd.arm_l_raise, gcmd.arm_r_raise,
                        gcmd.arm_l_spread, gcmd.arm_r_spread]):
                    self._bus.publish(b"CTX_ARM_GESTURE", {
                        "arm_l_raise":    gcmd.arm_l_raise,
                        "arm_r_raise":    gcmd.arm_r_raise,
                        "arm_l_spread":   gcmd.arm_l_spread,
                        "arm_r_spread":   gcmd.arm_r_spread,
                        "wrist_l_rotate": gcmd.wrist_l_rotate,
                        "wrist_r_rotate": gcmd.wrist_r_rotate,
                        "duration_s":     gcmd.duration_s,
                        "source":         "gesture_engine",
                        "return_to_rest": True,  # always return after gesture
                    })

        time.sleep(gcmd.duration_s)
        self._current_gesture = None

    def _idle_loop(self):
        """Generate subtle idle animations during silence."""
        import random
        idle_set = ["idle_micro_left", "idle_micro_right", "idle_breathe"]
        while self._running:
            time.sleep(self.IDLE_INTERVAL_S + random.uniform(-2, 2))
            idle_time = time.time() - self._last_gesture_t
            if idle_time > self.IDLE_INTERVAL_S:
                with self._lock:
                    if not self._gesture_q:
                        gname = random.choice(idle_set)
                        self._gesture_q.append(GESTURES[gname])

    def _dispatch_loop(self):
        """Consume the gesture queue."""
        while self._running:
            gcmd = None
            with self._lock:
                if self._gesture_q:
                    gcmd = self._gesture_q.pop(0)
            if gcmd:
                self._execute(gcmd)
            else:
                time.sleep(0.1)

    def start(self):
        self._running = True
        threading.Thread(target=self._dispatch_loop, daemon=True).start()
        threading.Thread(target=self._idle_loop,     daemon=True).start()
        logger.info("GestureEngine started | idle + emotion-driven gestures active")

    def stop(self):
        self._running = False
