#!/usr/bin/env python3
"""
deploy/scripts/gen_aws_inventory.py — Bubo Unified V10
Generates Ansible inventory from running AWS EC2 instances.
Run after CloudFormation stack is ready.

Usage:
  python3 deploy/scripts/gen_aws_inventory.py \
    --env bubo-prod --region us-east-1 \
    --output deploy/ansible/inventories/aws/hosts.ini
"""

import argparse, subprocess, json, sys, pathlib

def get_instances(env: str, region: str) -> list:
    """Query EC2 for all Bubo instances in the given environment."""
    try:
        result = subprocess.run([
            "aws", "ec2", "describe-instances",
            "--filters",
            f"Name=tag:Project,Values=Bubo",
            f"Name=tag:BuboEnvironment,Values={env}",
            "Name=instance-state-name,Values=running",
            "--query", "Reservations[*].Instances[*].{"
                       "id:InstanceId,type:InstanceType,"
                       "public_ip:PublicIpAddress,private_ip:PrivateIpAddress,"
                       "role:Tags[?Key=='BuboRole']|[0].Value,"
                       "state:State.Name}",
            "--output", "json",
            "--region", region,
        ], capture_output=True, text=True, timeout=15)
        if result.returncode != 0:
            print(f"AWS CLI error: {result.stderr}", file=sys.stderr)
            return []
        data = json.loads(result.stdout)
        # Flatten nested list
        instances = []
        for group in data:
            for inst in group:
                if inst.get("role") and inst.get("state") == "running":
                    instances.append(inst)
        return instances
    except Exception as e:
        print(f"Error querying EC2: {e}", file=sys.stderr)
        return []


ROLE_PORT = {
    "gateway": 5599, "limbic": 5621, "memory": 5643,
    "social":  5609, "cortex": 5600, "llm":    8080,
}

ROLE_GROUP = {
    "gateway": "bubo_gateway", "limbic": "bubo_limbic",
    "memory":  "bubo_memory",  "social": "bubo_social",
    "cortex":  "bubo_cortex",  "llm":    "bubo_llm",
}


def generate_inventory(instances: list, ssh_key: str = "~/.ssh/bubo_id_ed25519",
                        env: str = "bubo-prod", profile: str = "aws_api") -> str:
    """Generate INI-format Ansible inventory."""
    groups: dict = {g: [] for g in ROLE_GROUP.values()}
    groups["bubo_llm"] = []

    for inst in instances:
        role  = inst.get("role", "").lower()
        group = ROLE_GROUP.get(role)
        if not group:
            continue
        ip   = inst.get("public_ip") or inst.get("private_ip", "")
        port = ROLE_PORT.get(role, 5600)
        line = (f"{role}  ansible_host={ip}  "
                f"bubo_role={role}  bubo_port={port}  "
                f"instance_type={inst.get('type','unknown')}")
        groups[group].append(line)

    lines = [
        f"# Auto-generated by gen_aws_inventory.py",
        f"# Environment: {env}  Profile: {profile}",
        f"# Instances: {len(instances)}",
        "",
    ]

    for group_name, hosts in groups.items():
        if hosts:
            lines.append(f"[{group_name}]")
            lines.extend(hosts)
            lines.append("")

    # Add children group
    active_groups = [g for g, h in groups.items() if h]
    if active_groups:
        lines.append("[bubo_cloud:children]")
        for g in active_groups:
            lines.append(g)
        lines.append("")

    lines.extend([
        "[all:vars]",
        "ansible_user=ubuntu",
        f"ansible_ssh_private_key_file={ssh_key}",
        "ansible_ssh_common_args='-o StrictHostKeyChecking=no'",
        f"bubo_profile={profile}",
        "bubo_venv=/opt/bubo/venv",
        "bubo_home=/opt/bubo",
        "bubo_version=9000",
    ])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--env",     default="bubo-prod")
    parser.add_argument("--region",  default="us-east-1")
    parser.add_argument("--output",  default="-")
    parser.add_argument("--key",     default="~/.ssh/bubo_id_ed25519")
    parser.add_argument("--profile", default="aws_api")
    args = parser.parse_args()

    instances = get_instances(args.env, args.region)
    if not instances:
        print(f"No running Bubo instances found in {args.env} ({args.region})",
              file=sys.stderr)
        # Write a minimal placeholder inventory so Ansible doesn't fail
        inventory = f"# No instances running — deploy CloudFormation stack first\n[all]\n"
    else:
        print(f"Found {len(instances)} instances", file=sys.stderr)
        inventory = generate_inventory(instances, args.key, args.env, args.profile)

    if args.output == "-":
        print(inventory)
    else:
        pathlib.Path(args.output).parent.mkdir(parents=True, exist_ok=True)
        pathlib.Path(args.output).write_text(inventory)
        print(f"Inventory written: {args.output}  ({len(instances)} hosts)",
              file=sys.stderr)


if __name__ == "__main__":
    main()
