# ptp4l.conf — Bubo v50.0 slave (all nodes except hypothalamus)
[global]
domainNumber            0
time_stamping           hardware
delay_mechanism         E2E
twoStepFlag             0
logSyncInterval         -3
logMinDelayReqInterval  0
logAnnounceInterval     1
announceReceiptTimeout  3
priority1               128
priority2               128
clockClass              255
pi_proportional_const   0.7
pi_integral_const       0.3
step_threshold          0.000100000
first_step_threshold    0.000000200
verbose                 1
logging_level           5
