[all:vars]
ansible_user=brain
ansible_ssh_private_key_file=~/.ssh/bubo_id_ed25519
ansible_python_interpreter=/usr/bin/python3

[jetson_orin]
hypothalamus  ansible_host=192.168.1.12  brain_role=hypothalamus
thalamus-l    ansible_host=192.168.1.13  brain_role=thalamus_l
insula        ansible_host=192.168.1.15  brain_role=insula
thalamus-r    ansible_host=192.168.1.18  brain_role=thalamus_r

[jetson_nano_4gb]
hippocampus   ansible_host=192.168.1.30  brain_role=hippocampus
amygdala      ansible_host=192.168.1.31  brain_role=amygdala
cerebellum    ansible_host=192.168.1.32  brain_role=cerebellum
basal-ganglia ansible_host=192.168.1.33  brain_role=basal_ganglia
association   ansible_host=192.168.1.34  brain_role=association

[jetson_nano_2gb]
visual        ansible_host=192.168.1.50  brain_role=visual_cortex  saccadic_masking=true
auditory      ansible_host=192.168.1.51  brain_role=auditory        saccadic_masking=true
somatosensory ansible_host=192.168.1.52  brain_role=somatosensory
spinal-arms   ansible_host=192.168.1.53  brain_role=spinal_arms

[beagleboard]
sup-colliculus ansible_host=192.168.1.60  brain_role=superior_colliculus
spinal-legs    ansible_host=192.168.1.61  brain_role=spinal_legs

[all_brain:children]
jetson_orin
jetson_nano_4gb
jetson_nano_2gb
beagleboard

